version: "3.0"

services:
  nginx:
    image: nginx:1.21.1-alpine
    hostname: ppeop_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-html:/usr/share/nginx/html:ro
    ports:
      - 80:80
    links:
      - web
      - api
    restart: always

  web:
    image: protopie/enterprise-onpremises:web-14.3.0
    hostname: ppeop_web
    restart: always

  api:
    image: protopie/enterprise-onpremises:api-14.3.0
    hostname: ppeop_api
    env_file:
      - api.env
      - db.env
    volumes:
      - api_logs:/app/logs
      - api_upload:/app/upload
      - api_download:/app/download
      - ./default:/app/default
      - ./config.yml:/app/resources/config.yml:ro
      - ./license.pem:/app/resources/license.pem:ro
    links:
      - db
    restart: always

  db:
    image: postgres:10.5-alpine
    hostname: ppeop_db
    env_file: db.env
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./db-init/01-init.sh:/docker-entrypoint-initdb.d/01-init.sh:ro
      - ./db-init/02-init-db.sh:/docker-entrypoint-initdb.d/02-init-db.sh:ro
    restart: always

volumes:
  api_logs: {}
  api_upload: {}
  api_download: {}
  pg_data: {}
