#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "${POSTGRES_USER}" <<-EOSQL
  CREATE DATABASE ${DB_DATABASE} ENCODING 'UTF-8' LC_COLLATE 'C' LC_CTYPE 'C' TEMPLATE 'template0';

  CREATE USER ${DB_READ_USER} PASSWORD '${DB_READ_PASSWORD}';
  CREATE USER ${DB_WRITE_USER} PASSWORD '${DB_WRITE_PASSWORD}' IN ROLE ${DB_READ_USER};
EOSQL
