#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "${POSTGRES_USER}" --dbname "${DB_DATABASE}" <<-EOSQL
  CREATE EXTENSION IF NOT EXISTS pgcrypto;
  CREATE EXTENSION IF NOT EXISTS pg_trgm;

  ALTER DEFAULT PRIVILEGES FOR ROLE ${DB_WRITE_USER} IN SCHEMA public
    GRANT SELECT ON TABLES TO ${DB_READ_USER};
EOSQL
